import type { Metadata } from "next";
import "./globals.css";
import EAFooter from "./components/footer";
import Image from "next/image";
import EAlogo from "./assets/EAthink.png";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className=" bg-green-700 h-16 ">
          <div className="max-w-screen-sm grid grid-cols-4 md:grid-cols-3 place-items-center m-auto md:max-w-screen-md">
            <p className="col-span-2 md:col-span-1 text-lg my-auto ml-4 hover:scale-110 transition-all duration-300 ease-in md:hover:scale-125 md:text-xl md:ml-0 lg:text-3xl">
              Loot Box Simulator
            </p>
            <Link href={"/"} className="w-16 h-16">
              <Image
                src={EAlogo}
                alt="EA logo."
                placeholder="empty"
                className="w-16 h-16 hover:scale-95 transition-all duration-300 ease-out"
              ></Image>
            </Link>
            <Link
              className="text-lg my-auto hover:underline hover:scale-110 transition-all duration-300 ease-in md:hover:scale-125 md:text-xl lg:text-3xl"
              href={"/"}
            >
              Prizes
            </Link>
          </div>
        </header>
        <main className=" max-w-screen-lg m-auto">{children}</main>
        <EAFooter />
      </body>
    </html>
  );
}
